services:
# --- CHỈ CHẠY ỨNG DỤNG JAVA API (DÙNG CHUNG MYSQL CỦA DỰ ÁN CŨ) ---
  java-app-api:
    build:
      context: .
      dockerfile_inline: |
        FROM maven:3.9.6-eclipse-temurin-21-alpine
        WORKDIR /app
    restart: unless-stopped    
    container_name: MyJavaApp_4_Clean_Architecture_API
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8081:8080" # Đổi cổng bên ngoài thành 8081 để tránh trùng với dự án cũ (8080)
      - "5006:5005" # Đổi từ "5006:5005" để bebug ngay trong docker
    environment:
      # 🌟 KẾT NỐI: Trỏ trực tiếp về mysql-container của dự án cũ và dùng chung schema biến ${MYSQL_DATABASE}
      DB_URL: "jdbc:mysql://MySQL_SpringBoot_Clean_Architecture:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      DB_USERNAME: "root"
      DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - .:/app
      - /app/target/
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xms512m -Xmx1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    
# 🌟 GIA NHẬP MẠNG: Đưa container này vào chung mạng nội bộ với dự án 3_Clean_Architecture_WEB
    networks:
      - springboot_network

    # 🌟 TỰ ĐỘNG ĐỒNG BỘ: Kích hoạt tính năng Watch cho dự án mới
    develop:
      watch:
        - action: rebuild
          path: ./pom.xml
# --- ĐỊNH NGHĨA KẾT NỐI MẠNG NGOÀI ---
networks:
  springboot_network:
    external: true
    name: 3_clean_architecture_web_default